name: CodeQL AND Semgrep Check

on:
  workflow_call:
    outputs:
      checks-passed:
        description: "Indicates if all checks passed"
        value: ${{ jobs.check-status.outputs.success }}

# permission in following order
# read workflow files, read repo contents
# write security event and read packages
permissions:
  actions: read
  contents: read
  security-events: write
  packages: read

jobs:
  codeql:
    name: CodeQL
    uses: ./.github/workflows/codeql.yml

  semgrep:
    name: Semgrep
    uses: ./.github/workflows/semgrep-rules.yml

  check-status:
    needs: [codeql, semgrep]
    runs-on: ubuntu-24.04
    outputs:
      success: ${{ steps.check.outputs.success }}
    steps:
      - id: check
        run: |
          if [[ "${{ needs.codeql.result }}" == "success" ]]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
